name: CI Pipeline

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Java installieren
        uses: actions/setup-java@v3
        with:
          java-version: '21'

      - name: Gradle Wrapper ausführbar machen
        run: chmod +x ./gradlew

      - name: Abhängigkeiten installieren
        run: ./gradlew build -x test

      - name: Projekt bauen
        run: ./gradlew assemble

