name: CI Pipeline

on:
  push:
    branches:
      - main
      - 'feature/*'
      - 'bug/*'
    paths:
      - 'Code/airport-service/**'
      - 'Code/flight-service/**'
  pull_request:
    branches:
      - main
      - 'feature/*'
    paths:
      - 'Code/airport-service/**'
      - 'Code/flight-service/**'

env:
  JAVA_VERSION: '21'
  GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.caching=true'

jobs:
  # Job 1: Unit Tests
  test:
    name: Unit Tests (${{ matrix.service }})
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      checks: write
      pull-requests: write

    strategy:
      fail-fast: false
      matrix:
        service: [airport-service, flight-service]

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Java installieren
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'

      - name: Gradle Wrapper ausführbar machen
        run: chmod +x ./Code/${{ matrix.service }}/gradlew

      - name: Unit Tests ausführen
        working-directory: ./Code/${{ matrix.service }}
        run: ./gradlew test --no-daemon --console=plain

      - name: Test Report veröffentlichen
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Unit Test Report (${{ matrix.service }})
          path: ./Code/${{ matrix.service }}/build/test-results/test/*.xml
          reporter: java-junit

      - name: Test Coverage Report hochladen
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ matrix.service }}
          path: ./Code/${{ matrix.service }}/build/reports/tests/test/
          retention-days: 7

  # Job 2
  build:
    name: Build Application (${{ matrix.service }})
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 20
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        service: [airport-service, flight-service]
        include:
          - service: airport-service
            db_name: airports_db
          - service: flight-service
            db_name: flights_db
      
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Java installieren
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'

      - name: Leere Datenbank erstellen
        run: |
          mysql -h 127.0.0.1 -u root -proot -e "CREATE DATABASE IF NOT EXISTS ${{ matrix.db_name }};"
          mysql -h 127.0.0.1 -u root -proot -e "SHOW DATABASES;"

      - name: Gradle Wrapper ausführbar machen
        run: chmod +x ./Code/${{ matrix.service }}/gradlew

      - name: Application bauen
        working-directory: ./Code/${{ matrix.service }}
        run: ./gradlew build -x test --no-daemon --console=plain --build-cache
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/${{ matrix.db_name }}?useSSL=false&serverTimezone=UTC
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: root

      - name: JAR-Datei umbenennen (mit Version)
        working-directory: ./Code/${{ matrix.service }}/build/libs
        run: |
          COMMIT_SHORT=$(git rev-parse --short HEAD)
          for file in *.jar; do
            if [ -f "$file" ]; then
              mv "$file" "${{ matrix.service }}-${COMMIT_SHORT}.jar"
            fi
          done

      - name: Build-Artefakte speichern
        uses: actions/upload-artifact@v4
        with:
          name: application-jar-${{ matrix.service }}
          path: ./Code/${{ matrix.service }}/build/libs/*.jar
          retention-days: 30

      - name: Build-Grösse ausgeben
        working-directory: ./Code/${{ matrix.service }}/build/libs
        run: |
          echo "### Build Information (${{ matrix.service }})" >> $GITHUB_STEP_SUMMARY
          echo "- **JAR Size:** $(du -h *.jar | cut -f1)" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit:** $(git rev-parse --short HEAD)" >> $GITHUB_STEP_SUMMARY
          echo "- **Build Time (UTC):** $(date -u '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_STEP_SUMMARY
          echo "- **Build Time (CH):** $(TZ='Europe/Zurich' date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_STEP_SUMMARY

  # Job 3: API Tests
  api-tests:
    name: API Tests (${{ matrix.service }})
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 10
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        service: [airport-service, flight-service]
        include:
          - service: airport-service
            port: 8080
          - service: flight-service
            port: 8081

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Java installieren
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'

      - name: Gradle Wrapper ausführbar machen
        run: chmod +x ./Code/${{ matrix.service }}/gradlew

      - name: Application starten (Hintergrund)
        working-directory: ./Code/${{ matrix.service }}
        run: |
          ./gradlew bootRun > app.log 2>&1 &
          echo $! > app.pid
          echo "Started ${{ matrix.service }} with PID: $(cat app.pid)"

      - name: Warten bis Service bereit ist
        run: |
          echo "⏳ Warte auf ${{ matrix.service }} auf Port ${{ matrix.port }}..."
          for i in {1..30}; do
            if curl -f http://localhost:${{ matrix.port }}/actuator/health 2>/dev/null; then
              echo "✅ ${{ matrix.service }} ist bereit!"
              exit 0
            fi
            echo "Versuch $i/30..."
            sleep 2
          done
          echo "❌ ${{ matrix.service }} konnte nicht gestartet werden"
          echo "=== Application Logs ==="
          cat ./Code/${{ matrix.service }}/app.log
          exit 1

      - name: Newman installieren
        run: npm install -g newman newman-reporter-htmlextra

      - name: Postman Collection ausführen
        working-directory: ./Code/${{ matrix.service }}
        run: |
          newman run REST API- ${{ matrix.service }}.postman_collection.json \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export postman-report.html \
            --reporter-htmlextra-title "${{ matrix.service }} API Tests"

      - name: Service stoppen
        if: always()
        working-directory: ./Code/${{ matrix.service }}
        run: |
          if [ -f app.pid ]; then
            kill $(cat app.pid) || true
            echo "✅ ${{ matrix.service }} gestoppt"
          fi

      - name: Application Logs hochladen
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.service }}
          path: ./Code/${{ matrix.service }}/app.log
          retention-days: 3

      - name: Postman Report hochladen
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: postman-report-${{ matrix.service }}
          path: ./Code/${{ matrix.service }}/postman-report.html
          retention-days: 7