name: CI Pipeline

on:
  push:
    branches:
      - main
      - 'feature/*'
    paths:
      - 'Code/airport-service/**'
      - 'Code/flight-service/**'
  pull_request:
    branches:
      - main
      - 'feature/*'
    paths:
      - 'Code/airport-service/**'
      - 'Code/flight-service/**'

env:
  JAVA_VERSION: '21'
  GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.caching=true'

jobs:
  # Job 1
  test:
    name: Unit Tests (${{ matrix.service }})
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      checks: write
      pull-requests: write

    strategy:
      fail-fast: false
      matrix:
        service: [airport-service, flight-service]

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Java installieren
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'

      - name: Gradle Wrapper ausführbar machen
        run: chmod +x ./Code/${{ matrix.service }}/gradlew

      - name: Unit Tests ausführen
        working-directory: ./Code/${{ matrix.service }}
        run: ./gradlew test --no-daemon --console=plain

      - name: Test Report veröffentlichen
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Unit Test Report (${{ matrix.service }})
          path: ./Code/${{ matrix.service }}/build/test-results/test/*.xml
          reporter: java-junit

      - name: Test Coverage Report hochladen
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ matrix.service }}
          path: ./Code/${{ matrix.service }}/build/reports/tests/test/
          retention-days: 7

  # Job 2
  build:
    name: Build Application (${{ matrix.service }})
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 20
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        service: [airport-service, flight-service]

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Java installieren
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'

      - name: Gradle Wrapper ausführbar machen
        run: chmod +x ./Code/${{ matrix.service }}/gradlew

      - name: Application bauen
        working-directory: ./Code/${{ matrix.service }}
        run: ./gradlew build -x test --no-daemon --console=plain --build-cache

      - name: JAR-Datei umbenennen (mit Version)
        working-directory: ./Code/${{ matrix.service }}/build/libs
        run: |
          COMMIT_SHORT=$(git rev-parse --short HEAD)
          for file in *.jar; do
            if [ -f "$file" ]; then
              mv "$file" "${{ matrix.service }}-${COMMIT_SHORT}.jar"
            fi
          done

      - name: Build-Artefakte speichern
        uses: actions/upload-artifact@v4
        with:
          name: application-jar-${{ matrix.service }}
          path: ./Code/${{ matrix.service }}/build/libs/*.jar
          retention-days: 30

      - name: Build-Grösse ausgeben
        working-directory: ./Code/${{ matrix.service }}/build/libs
        run: |
          echo "### Build Information (${{ matrix.service }})" >> $GITHUB_STEP_SUMMARY
          echo "- **JAR Size:** $(du -h *.jar | cut -f1)" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit:** $(git rev-parse --short HEAD)" >> $GITHUB_STEP_SUMMARY
          echo "- **Build Time (UTC):** $(date -u '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_STEP_SUMMARY
          echo "- **Build Time (CH):** $(TZ='Europe/Zurich' date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_STEP_SUMMARY