name: CI Pipeline

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Java installieren
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Gradle Wrapper ausführbar machen
        run: chmod +x ./airport-service/gradle-wrapper

      - name: Abhängigkeiten installieren
        run: ./airport-service/gradle-wrapper build -x test

      - name: Projekt bauen
        run: ./airport-service/gradle-wrapper assemble


      - name: Projekt bauen
        run: ./gradle-wrapper assemble

