name: Multi-Environment Pipeline

on:
  push:
    branches:
      - main
      - develop
      - 'feature/*'
    paths:
      - 'Code/airport-service/**'
      - 'Code/flight-service/**'

env:
  JAVA_VERSION: '21'

jobs:
  # DEV Environment
  deploy-dev:
    name: Deploy to Development
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/heads/feature/')
    environment:
      name: dev
      url: https://dev-api.example.com
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Deploy to Dev
        run: |
          echo "Deploying to Development Environment"
          echo "Environment: DEV"
          echo "Services: airport-service, flight-service"

  # QA Environment
  deploy-qa:
    name: Deploy to QA
    runs-on: ubuntu-latest
    needs: deploy-dev
    if: github.ref == 'refs/heads/develop'
    environment:
      name: qa
      url: https://qa-api.example.com
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Deploy to QA
        run: |
          echo "Deploying to QA Environment"
          echo "Environment: QA"
          echo "Services: airport-service, flight-service"

  # PROD Environment
  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: deploy-qa
    if: github.ref == 'refs/heads/main'
    environment:
      name: prod
      url: https://api.example.com
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Deploy to Production
        run: |
          echo "Deploying to Production Environment"
          echo "Environment: PROD"
          echo "Services: airport-service, flight-service"